// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arrow': string;
  'list': string;
  'listItem': string;
  'opened': string;
  'select': string;
  'selectedArea': string;
}
export const cssExports: CssExports;
export default cssExports;
