// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkbox': string;
  'required': string;
  'checked': string;
  'left': string;
  'right': string;
  'disabled': string;
}
export const cssExports: CssExports;
export default cssExports;
