// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blink': string;
  'cursor': string;
}
export const cssExports: CssExports;
export default cssExports;
